### ISSUE TITLE
ADN

### ISSUE THREAD

**Issue by Mee42** [Mee42/mee42#5]
ADN is a content transfering server, made for quickly sharing code, images, and smaller files across the internet. https://adn.mee42.dev

## TODO
- [ ] web interface for sending stuff
- [ ] bigger file support
- [ ] filesystem support for storage
- [ ] able to upload said bigger files with the web interface (this means buffering requests)
